project:
  type: website
  resources: assets

website:
  title: "Zachary R. Pipping"
  navbar:
    background: "#00008b"
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/gzacharypipping
        target: blank
      - icon: github
        href: https://github.com/zachbtw
      - icon: file-pdf
        href: assets/resume.pdf

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto

